<?php

return [
    'actions' => [
        'view' => '查看',
        'create' => '新增',
        'update' => '编辑',
        'delete' => '删除',
    ],

    'modules' => [
        'dashboard' => [
            'label' => '工作台',
            'group' => '工作台',
            'model' => null,
            'sort' => 0,
        ],
        'banners' => [
            'label' => '轮播图',
            'group' => '官网管理',
            'model' => \App\Models\Banner::class,
            'sort' => 10,
        ],
        'home_sections' => [
            'label' => '首页模块',
            'group' => '官网管理',
            'model' => \App\Models\HomeSection::class,
            'sort' => 20,
        ],
        'site_nav_menus' => [
            'label' => '菜单管理',
            'group' => '官网管理',
            'model' => \App\Models\SiteNavMenu::class,
            'sort' => 30,
        ],
        'site_partners' => [
            'label' => '合作伙伴',
            'group' => '官网管理',
            'model' => \App\Models\SitePartner::class,
            'sort' => 40,
        ],
        'site_statistics' => [
            'label' => '数据指标',
            'group' => '官网管理',
            'model' => \App\Models\SiteStatistic::class,
            'sort' => 50,
        ],
        'categories' => [
            'label' => '产品分类',
            'group' => '产品管理',
            'model' => \App\Models\Category::class,
            'sort' => 10,
        ],
        'products' => [
            'label' => '产品列表',
            'group' => '产品管理',
            'model' => \App\Models\Product::class,
            'sort' => 20,
        ],
        'product_consultations' => [
            'label' => '产品咨询',
            'group' => '产品管理',
            'model' => \App\Models\ProductConsultation::class,
            'sort' => 30,
        ],
        'product_page_settings' => [
            'label' => '产品中心页面',
            'group' => '产品管理',
            'model' => \App\Models\ProductPageSetting::class,
            'sort' => 40,
        ],
        'case_study_categories' => [
            'label' => '案例分类',
            'group' => '案例管理',
            'model' => \App\Models\CaseStudyCategory::class,
            'sort' => 10,
        ],
        'case_studies' => [
            'label' => '案例列表',
            'group' => '案例管理',
            'model' => \App\Models\CaseStudy::class,
            'sort' => 20,
        ],
        'case_page_settings' => [
            'label' => '案例页设置',
            'group' => '案例管理',
            'model' => \App\Models\CasePageSetting::class,
            'sort' => 30,
        ],
        'article_categories' => [
            'label' => '新闻分类',
            'group' => '新闻管理',
            'model' => \App\Models\ArticleCategory::class,
            'sort' => 10,
        ],
        'articles' => [
            'label' => '新闻列表',
            'group' => '新闻管理',
            'model' => \App\Models\Article::class,
            'sort' => 20,
        ],
        'news_page_settings' => [
            'label' => '新闻页设置',
            'group' => '新闻管理',
            'model' => \App\Models\NewsPageSetting::class,
            'sort' => 30,
        ],
        'company_page_settings' => [
            'label' => '页面设置（总览）',
            'group' => '关于我们',
            'model' => \App\Models\CompanyPageSetting::class,
            'sort' => 10,
        ],
        'company_milestones' => [
            'label' => '发展历程',
            'group' => '关于我们',
            'model' => \App\Models\CompanyMilestone::class,
            'sort' => 20,
        ],
        'company_honors' => [
            'label' => '品牌荣誉（图片）',
            'group' => '关于我们',
            'model' => \App\Models\CompanyHonor::class,
            'sort' => 30,
        ],
        'company_team_members' => [
            'label' => '团队成员',
            'group' => '关于我们',
            'model' => \App\Models\CompanyTeamMember::class,
            'sort' => 40,
        ],
        'company_culture_values' => [
            'label' => '企业文化条目',
            'group' => '关于我们',
            'model' => \App\Models\CompanyCultureValue::class,
            'sort' => 50,
        ],
        'support_page_settings' => [
            'label' => '页面设置',
            'group' => '技术支持',
            'model' => \App\Models\SupportPageSetting::class,
            'sort' => 10,
        ],
        'support_documents' => [
            'label' => 'PDF 文档',
            'group' => '技术支持',
            'model' => \App\Models\SupportDocument::class,
            'sort' => 20,
        ],
        'support_videos' => [
            'label' => '教学视频',
            'group' => '技术支持',
            'model' => \App\Models\SupportVideo::class,
            'sort' => 30,
        ],
        'support_service_requests' => [
            'label' => '售后申请',
            'group' => '技术支持',
            'model' => \App\Models\SupportServiceRequest::class,
            'sort' => 40,
        ],
        'join_page_settings' => [
            'label' => '页面设置',
            'group' => '加入我们',
            'model' => \App\Models\JoinPageSetting::class,
            'sort' => 10,
        ],
        'join_job_categories' => [
            'label' => '岗位分类',
            'group' => '加入我们',
            'model' => \App\Models\JoinJobCategory::class,
            'sort' => 20,
        ],
        'join_positions' => [
            'label' => '开放岗位',
            'group' => '加入我们',
            'model' => \App\Models\JoinPosition::class,
            'sort' => 30,
        ],
        'join_applications' => [
            'label' => '简历投递',
            'group' => '加入我们',
            'model' => \App\Models\JoinApplication::class,
            'sort' => 40,
        ],
        'join_why_cards' => [
            'label' => '为什么加入',
            'group' => '加入我们',
            'model' => \App\Models\JoinWhyCard::class,
            'sort' => 50,
        ],
        'join_culture_cards' => [
            'label' => '文化条目',
            'group' => '加入我们',
            'model' => \App\Models\JoinCultureCard::class,
            'sort' => 60,
        ],
        'join_process_steps' => [
            'label' => '招聘流程',
            'group' => '加入我们',
            'model' => \App\Models\JoinProcessStep::class,
            'sort' => 70,
        ],
        'join_welfare_cards' => [
            'label' => '福利条目',
            'group' => '加入我们',
            'model' => \App\Models\JoinWelfareCard::class,
            'sort' => 80,
        ],
        'site_settings' => [
            'label' => '站点配置',
            'group' => '系统设置',
            'model' => \App\Models\SiteSetting::class,
            'sort' => 10,
        ],
        'site_footer_links' => [
            'label' => '页脚链接',
            'group' => '系统设置',
            'model' => \App\Models\SiteFooterLink::class,
            'sort' => 20,
        ],
        'site_social_links' => [
            'label' => '页脚社交',
            'group' => '系统设置',
            'model' => \App\Models\SiteSocialLink::class,
            'sort' => 30,
        ],
        'business_cos_settings' => [
            'label' => '业务配置',
            'group' => '系统设置',
            'model' => \App\Models\BusinessCosSetting::class,
            'sort' => 35,
        ],
        'admin_users' => [
            'label' => '用户管理',
            'group' => '系统设置',
            'model' => \App\Models\User::class,
            'sort' => 35,
        ],
        'roles' => [
            'label' => '角色管理',
            'group' => '系统设置',
            'model' => \App\Models\Role::class,
            'sort' => 40,
        ],
    ],
];
